# Generated by Django 4.1.7 on 2023-03-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampletext', models.CharField(default='sample text', max_length=100)),
            ],
        ),
    ]
