# Generated by Django 4.1.7 on 2023-03-25 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('sport', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('main_image', models.CharField(max_length=200)),
                ('second_image', models.CharField(max_length=200)),
                ('small_image_1', models.CharField(max_length=200)),
                ('small_image_2', models.CharField(max_length=200)),
                ('small_image_3', models.CharField(max_length=200)),
                ('small_image_4', models.CharField(max_length=200)),
                ('small_image_5', models.CharField(max_length=200)),
                ('small_image_6', models.CharField(max_length=200)),
                ('small_image_7', models.CharField(max_length=200)),
                ('small_image_8', models.CharField(max_length=200)),
                ('small_image_9', models.CharField(max_length=200)),
                ('small_image_10', models.CharField(max_length=200)),
                ('big_image_1', models.CharField(max_length=200)),
                ('big_image_2', models.CharField(max_length=200)),
                ('big_image_3', models.CharField(max_length=200)),
                ('big_image_4', models.CharField(max_length=200)),
                ('big_image_5', models.CharField(max_length=200)),
                ('big_image_6', models.CharField(max_length=200)),
                ('big_image_7', models.CharField(max_length=200)),
                ('big_image_8', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
