# Generated by Django 4.1.7 on 2023-03-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='size',
        ),
        migrations.AddField(
            model_name='shop',
            name='size_10UK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_11UK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_12UK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_5UK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_6UK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_7UK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_8UK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_9UK',
            field=models.IntegerField(default=0),
        ),
    ]
