# Generated by Django 4.1.7 on 2023-03-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_big_image_1_alter_shop_big_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='small_id_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='small_id_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='small_id_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='small_id_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='small_id_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='small_id_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='small_id_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='small_id_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='small_id_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='small_id_9',
            field=models.IntegerField(default=0),
        ),
    ]
