# Generated by Django 4.1.7 on 2023-03-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_small_id_1_shop_small_id_10_shop_small_id_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='size_2XL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_L',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_M',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_S',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_XL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_XS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_sock_KXL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_sock_KXXL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_sock_L',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_sock_M',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_sock_S',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_sock_XL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='size_sock_XS',
            field=models.IntegerField(default=0),
        ),
    ]
