# Generated by Django 4.1.7 on 2023-03-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_size_2xl_shop_size_l_shop_size_m_shop_size_s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='small_id_1',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_id_10',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_id_2',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_id_3',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_id_4',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_id_5',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_id_6',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_id_7',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_id_8',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_id_9',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_image_10',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_image_2',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_image_3',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_image_4',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_image_5',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_image_6',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_image_7',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_image_8',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='small_image_9',
        ),
    ]
