# Generated by Django 4.1.7 on 2023-03-26 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_remove_shop_small_id_1_remove_shop_small_id_10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default=None, max_length=200)),
                ('info_hightlight_text_1', models.CharField(default=None, max_length=300)),
                ('info_hightlight_text_2', models.CharField(default=None, max_length=300)),
                ('info_hightlight_text_3', models.CharField(default=None, max_length=300)),
                ('info_hightlight_title_1', models.CharField(default=None, max_length=300)),
                ('info_hightlight_title_2', models.CharField(default=None, max_length=300)),
                ('info_hightlight_title_3', models.CharField(default=None, max_length=300)),
                ('info_hightlight_img_1', models.CharField(default=None, max_length=300)),
                ('info_hightlight_img_2', models.CharField(default=None, max_length=300)),
                ('info_hightlight_img_3', models.CharField(default=None, max_length=300)),
                ('info_description_text_1', models.CharField(default=None, max_length=300)),
                ('info_description_title_1', models.CharField(default=None, max_length=300)),
                ('info_description_img_1', models.CharField(default=None, max_length=300)),
                ('info_detail_1', models.CharField(default=None, max_length=300)),
                ('info_detail_2', models.CharField(default=None, max_length=300)),
                ('info_detail_3', models.CharField(default=None, max_length=300)),
                ('info_detail_4', models.CharField(default=None, max_length=300)),
                ('info_detail_5', models.CharField(default=None, max_length=300)),
                ('info_detail_6', models.CharField(default=None, max_length=300)),
                ('info_detail_7', models.CharField(default=None, max_length=300)),
                ('info_detail_8', models.CharField(default=None, max_length=300)),
                ('info_detail_9', models.CharField(default=None, max_length=300)),
                ('info_detail_10', models.CharField(default=None, max_length=300)),
                ('info_detail_11', models.CharField(default=None, max_length=300)),
                ('info_detail_12', models.CharField(default=None, max_length=300)),
                ('info_faq_question_1', models.CharField(default=None, max_length=300)),
                ('info_faq_question_2', models.CharField(default=None, max_length=300)),
                ('info_faq_question_3', models.CharField(default=None, max_length=300)),
                ('info_faq_question_4', models.CharField(default=None, max_length=300)),
                ('info_faq_question_5', models.CharField(default=None, max_length=300)),
                ('info_faq_answer_1', models.CharField(default=None, max_length=300)),
                ('info_faq_answer_2', models.CharField(default=None, max_length=300)),
                ('info_faq_answer_3', models.CharField(default=None, max_length=300)),
                ('info_faq_answer_4', models.CharField(default=None, max_length=300)),
                ('info_faq_answer_5', models.CharField(default=None, max_length=300)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
