# Generated by Django 4.1.7 on 2023-03-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shopinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='size_sock_KXL',
            new_name='sizesock_KXL',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='size_sock_KXXL',
            new_name='sizesock_KXXL',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='size_sock_L',
            new_name='sizesock_L',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='size_sock_M',
            new_name='sizesock_M',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='size_sock_S',
            new_name='sizesock_S',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='size_sock_XL',
            new_name='sizesock_XL',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='size_sock_XS',
            new_name='sizesock_XS',
        ),
    ]
