# Generated by Django 4.1.7 on 2023-04-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_categoryinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryinfo',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
