# Generated by Django 4.1.7 on 2023-04-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_categoryinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='info_description_text_1',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
