# Generated by Django 4.1.7 on 2023-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_shippingaddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
